INSERT INTO TIPO_PERSONAL
VALUES(DEFAULT,'Doctor');

INSERT INTO TIPO_PERSONAL
VALUES(DEFAULT,'Enfermero');

INSERT INTO TIPO_PERSONAL
VALUES(DEFAULT,'Administrativo');

INSERT INTO TIPO_MEDICINA
VALUES(1,'Hombres');

INSERT INTO TIPO_MEDICINA
VALUES(2,'Mujeres');

INSERT INTO TIPO_MEDICINA
VALUES(3,'Niños');

INSERT INTO ESTADO_CAMA
VALUES(1,'Disponible');

INSERT INTO ESTADO_CAMA
VALUES(2,'Reservado');

INSERT INTO EQUIPO_MEDICO
VALUES(1,'Luces Quirurgicas','Kalstein',50);

INSERT INTO EQUIPO_MEDICO
VALUES(2,'Ultrasonido','Eleinmsa',45);

INSERT INTO EQUIPO_MEDICO
VALUES(3,'Esterilizadores','Eleinmsa',25);

INSERT INTO EQUIPO_MEDICO
VALUES(4,'Desfibriladores','Eleinmsa',25);

INSERT INTO EQUIPO_MEDICO
VALUES(5,'Monitores','Eleinmsa',50);

INSERT INTO EQUIPO_MEDICO
VALUES(6,'Respiradores Artificiales','Eleinmsa',75);

INSERT INTO EQUIPO_MEDICO
VALUES(7,'Electrocardiografos','Eleinmsa',65);

INSERT INTO PROCEDIMIENTO_MEDICO
VALUES(1,'Apendicectomia',7);

INSERT INTO PROCEDIMIENTO_MEDICO
VALUES(2,'Biopsia de Mama',5);

INSERT INTO PROCEDIMIENTO_MEDICO
VALUES(3,'Cirugia de Cataratas',2);

INSERT INTO PROCEDIMIENTO_MEDICO
VALUES(4,'Cesarea',3);

INSERT INTO PROCEDIMIENTO_MEDICO
VALUES(5,'Histerectomia',6);

INSERT INTO PROCEDIMIENTO_MEDICO
VALUES(6,'Cirugia para la Lumbalgia',12);

INSERT INTO PROCEDIMIENTO_MEDICO
VALUES(7,'Mastectomia',5);

INSERT INTO PROCEDIMIENTO_MEDICO
VALUES(8,'Amigdalectomia',1);

